# Generated by Django 4.2.7 on 2023-11-01 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("url_shortner", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="url_short",
            new_name="urlshortner",
        ),
    ]
