# Generated by Django 4.2.7 on 2023-11-01 09:00

from django.db import migrations, models
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        ("url_shortner", "0002_rename_url_short_urlshortner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="urlshortner",
            name="short_url",
            field=models.CharField(
                default=shortuuid.main.ShortUUID.random, max_length=10, unique=True
            ),
        ),
    ]
