# Generated by Django 4.2.7 on 2023-11-01 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("url_shortner", "0003_alter_urlshortner_short_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="urlshortner",
            name="short_url",
            field=models.CharField(
                default="http://127.0.0.1:8000/<bound method ShortUUID.random of <shortuuid.main.ShortUUID object at 0x7f26a8e60af0>>",
                max_length=100,
                unique=True,
            ),
        ),
    ]
